### ISSUE TITLE
android port

### ISSUE THREAD

**Issue by ghost** [i5ik/jspaint.exe#20]
this might be not necesarry but can you do it for android and put this on google play or f-droid so i will use jspaint on my phone without internet

**Comment by crisdosaygo** [comment]
@lime360 For $2500 USD I can take a look at doing this for you. Can't guarantee it's possible tho, but you can pay me to take a look. Let me know if you are cool, and I'll send you a payment link.

**Comment by ghost** [comment]
I DONT HAVE A CREDIT CARD

**Comment by crisdosaygo** [comment]
NO worries. No need to yell! 🔽 If you have a bank it's still ok. My payment provider accepts 25 different methods, and many in EU. Thank you, sir! :P ;) xx ;p
