### ISSUE TITLE
Ubuntu doesn't work

### ISSUE THREAD

**Issue by TheLastGimbus** [i5ik/jspaint.exe#3]
Hi!
I downloaded this, and when I lunch it by double click, looks like this:

![image](https://user-images.githubusercontent.com/40139196/123967262-70856e00-d9b6-11eb-8f71-5cf08ce6c612.png)

When I launch it in terminal by `./jspaint.linux`, does this:
```
App launcher started.
Preparing app data directory.
Inflating app contents.
App process requested.
App process created.
Waiting for your system security checks: .
Request app start.
Request service start.
Service started.
Request user interface.
Request UI directories.
UI data and cache directory created.
Request interface connection.
User interface online.
Could not start UI (chrome). Because: {}
Error at Could not start UI (chrome). Because: {}
State complete subprocess.connected false
Launcher failed. Exiting in 5 seconds...
Exit status: failure
Exiting...
```
And shows same windows as above

**Comment by crisdosaygo** [comment]
Hey, sorry, do you have Chrome installed? You need it I think. 

I will check out Ubuntu to see if I can see this. I'll reopen if there's anything to add.
