### ISSUE TITLE
does not work on windows 7

### ISSUE THREAD

**Issue by severak** [i5ik/jspaint.exe#6]
```
C:\severak>jspaint.exe
Node.js is only supported on Windows 8.1, Windows Server 2012 R2, or higher.
Setting the NODE_SKIP_PLATFORM_CHECK environment variable to 1 skips this
check, but Node.js might not execute correctly. Any issues encountered on
unsupported platforms will not be fixed.
```

It should at least show MessageBox with error message to be usable by end users.

**Comment by crisdosaygo** [comment]
Nice, I guess perhaps I can use Node to set NODE_SKIP_PLATFORM_CHECK and try to run and create a messagebox...but I think that check would happen before I could set the env.

It [seems v13.14.0 is last version to work on Windows 7](https://www.centennialsoftwaresolutions.com/post/install-node-js-on-windows-7). I could roll-back grader-base to use v13.14.0 by default, and notify authors that if they switch to a later version, Windows 7 may not work.

I could try to patch the binaries somehow to avoid this check, or perhaps I can [set the env for Node via an .env file](https://github.com/nexe/nexe/issues/652). But not sure...

Interesting how to "dragrade gracefully" in case we try running on an unsupported platform...and interesting to think about if this is even the right approach, or if we go the the onus-on-author approach. 

Or even some other one

Thanks for the issue! :)

I think in the case of platforms that don't work, what I will aim for is not a GUI messagebox, as that will involve all the chrome launch code, but just keep it simple and print a message in the console, but keep the console open so people can read it.
