### ISSUE TITLE
monterey12.6.2 on macbookpro2016 can't run

### ISSUE THREAD

**Issue by hackdoors** [i5ik/jspaint.exe#9]
<img width="563" alt="image" src="https://user-images.githubusercontent.com/48487393/215709069-c472bd36-8a06-4baf-9b68-878ffc8bd6f3.png">
as you can see ,i download the x86cpu jspaint.macos,but didn't work
i also download the latest jspaint-macos,but it is on arm

sorry to ask the stupided question,but i relealy don't know how to solute it

**Comment by crisdosaygo** [comment]
Thanks for this report @hackdoors ! I'll take a look later--may take me about 2 weeks: busy right now!

**Comment by crisdosaygo** [comment]
hey man I fixed this for you @hackdoors
